### ISSUE TITLE
Sharing iP code quality feedback [for @Javiery3889]

### ISSUE THREAD

**Issue by soc-se-bot-blue** [Javiery3889/ip#4]
@Javiery3889 We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/Blu/task/Task.java` lines `38-40`](https://github.com/Javiery3889/ip/blob/7d87ea8e75bec98bfb356d90ca7acccccf809305/src/main/java/Blu/task/Task.java#L38..L40):

```java

    /**
     * Unmark the task as not completed.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

possible problems in commit [`a8900ef`](https://github.com/Javiery3889/ip/commit/a8900ef405a44cbf5f847bea57b3d765612bbad0):

```

Fixed bug where welcome message is not displayed

Upon startup, Blu does not display welcome message as expected.
This is because the method to display the welcome message is
never called in the application.

Create the welcome message in init() and displays it in start().
Change welcome message to include canonical path of the storage
file instead.

This allows users to locate the file path easily.


```

* Not in imperative mood (?)
             

**Suggestion:** Follow the given [conventions for Git commit messages](https://se-education.org/guides/conventions/git.html) for _future_ commits (do not modify past commit messages as doing so will change the commit timestamp that we used to detect your commit timings).

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by Javiery3889** [comment]
Header comment fixed in cd72538.
